### ISSUE TITLE
Current map version is not compatible with current stable engine version 7621

### ISSUE THREAD

**Issue by ssoloff** [triplea-maps/invasion_usa#16]
#### Environment

TripleA engine version: 1.9.0.0.7621 (latest stable)
Map version: `master` at commit ca7f9f9 (2018-02-22T22:28:16-0500)

#### Description

When attempting to select the Invasion USA map, the following errors are reported in the console:

```
SAXParseException: game: Invasion USA, line: 447, column: 54, error: Attribute "isDisplayedFor" must be declared for element type "resource".
Could not parse:jar:file:/home/ssoloff/triplea/downloadedMaps/invasion_usa-master.zip!/invasion_usa-master/map/games/Invasion_USA.xml
games.strategy.engine.data.GameParseException: MapName: jar:file:/home/ssoloff/triplea/downloadedMaps/invasion_usa-master.zip!/invasion_usa-master/map/games/Invasion_USA.xml, The following option name of unitAttachment of class UnitAttachment are either misspelled or exist only in a future version of TripleA. Setter: isLandTransportable
	at games.strategy.engine.data.GameParser.setValues(GameParser.java:1248)
	at games.strategy.engine.data.GameParser.parseAttachments(GameParser.java:1200)
	at games.strategy.engine.data.GameParser.parse(GameParser.java:150)
	at games.strategy.engine.framework.ui.GameChooserEntry.fullyParseGameData(GameChooserEntry.java:60)
	at games.strategy.engine.framework.startup.ui.GameSelectorPanel.lambda$selectGameFile$233(GameSelectorPanel.java:390)
	at games.strategy.engine.framework.ui.background.BackgroundTaskRunner.lambda$runInBackground$285(BackgroundTaskRunner.java:43)
	at games.strategy.engine.framework.ui.background.BackgroundTaskRunner.lambda$runInBackgroundAndReturn$286(BackgroundTaskRunner.java:71)
	at games.strategy.engine.framework.ui.background.BackgroundTaskRunner$1.doInBackground(BackgroundTaskRunner.java:114)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
SAXParseException: game: Invasion USA, line: 447, column: 54, error: Attribute "isDisplayedFor" must be declared for element type "resource".
```

Looks like the map is using features (`isLandTransportable` and `isDisplayedFor`) not available in the latest stable engine (7621).  Not sure if this was intentional, but it will prevent users from playing this map unless they upgrade to a pre-release engine version (typically only done by advanced users).

@ron-murhammer

**Comment by ron-murhammer** [comment]
@ssoloff Yeah, I'm guessing its intentional as he's currently working on updating it. I think TWW may parse but is using a number of features not in 7621. Honestly we really need to update the stable as its getting way outdated.

**Comment by ssoloff** [comment]
@ron-murhammer I don't follow the map making threads on the forum much, but I thought map makers would create a "beta" XML, or something like that, with pre-release features until stable was upgraded (I think that's what TWW is doing).

**Comment by ron-murhammer** [comment]
@ssoloff Depends on the map maker but yes many will create a second 'beta' XML and just include both XMLs.

**Comment by WCSumpton** [comment]
Current version should now work with release 7641.

**Comment by ssoloff** [comment]
Confirmed.  Thank you!
